name: Build LaTeX PDF

on:
  push:
    paths:
      - 'workflows.tex'
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-full
      - name: Compile LaTeX
        run: pdflatex workflows.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflows-pdf
          path: workflows.pdf
